slug = "Filter-1"
title = "Filter 1.0"
author = "Stephen"
value = 30
description = """What's up everyone? I'm just an intern here, learning how to prevent XSS attacks! My filters here are unbreakable, I'm pretty sure. At least, I think covered everything that could be used for XSS.

I've got my filter all loaded up and ready to protect a super-secret flag on this [site](http://filter1.acmcyber.com:10000). I'm so sure you can't break it that I'll visit any link you send me [here](http://acmcyber.com:10001)."""
tags = ["xss"]
files = []
flag = "flag{uNbReAkAbLe_tHeY_sAiD_B-0}"
enabled = true
