slug = "Filter-1"
title = "Filter 1.0"
author = "Stephen"
value = 30
description = """What's up everyone? I'm just an intern here, learning how to prevent XSS attacks! My filters here are unbreakable, I'm pretty sure. At least, I think covered everything that could be used for XSS.

The admin has a cookie containing the flag on this [postbin](http://postbin1.acmcyber.com:10000). Report links you want the admin to visit [here](http://acmcyber.com:10001)."""
tags = ["xss"]
files = []
flag = "flag{uNbReAkAbLe_tHeY_sAiD_B-0}"
enabled = true
