slug = "do-not-enter"
title = "Do Not Enter"
author = "Yunfan"
value = 10
description = """
I'm building a website to start a business selling premium wool pants for hairless cats, but I have a problem: someone keeps accessing my private inventory pages and deleting my entries! I tried renaming the page to "DO NOT ENTER", but it didn't work...I know users should only be allowed to access 3 pages ("Home", "About Me", "BUY NOW!!1!!!11"), so what is the best method of preventing them from accessing my private files?
(P.S. I actually haven't made any sales yet so I can't pay you, but I can send you 3 FREE pairs of pants + this is great exposure :) )
Format your answer as flag{answer} with just one word (the core idea of the answer).
"""
tags = [ "trivia" ]
files = []
flag = "flag{whitelist}"
enabled = true