slug = "new-labs-2"
title = "New Labs 2"
author = "Steph"
value = 20
description = """After the data breach, some employees have started to protect their notes upon login. Unfortunately for us, this makes it harder to  steal information :( We heard that the founder uploaded a clue that they found in their travels to their account, but it looks like they have protected their notes. We only managed to find their username “c_bert” , but their password doesn’t seem to appear anywhere in the database. Hopefully you’ll have better luck finding the clue!"""
tags = [ "sql" ]
files = []
flag = "flag{f0ll0w_th3_s0urc3}"
enabled = true