slug = "royal-riddles"
title = "Royal Riddles"
author = "Sophia" 
value = 20
description = """numbers and words are one and the same.
so can you honestly tell me
alex ku kp b reqi ? 

Enter the flag as flag{decoded_message} with everything lowercase and words separated by underscores."""

tags = ["classical"]
files = []
flag = "flag{what_is_in_a_name}"
enabled = true
