slug = "new-labs-3"
title = "New Labs 3"
author = "Ted"
value = 35
description = """Our analysis team has made a breakthrough in collaboration with our spy team. Our spies have reported that there is a prized legendary gif under surveillance by CY_Labs. However, they have worked hard to keep its appearance hidden. This is what the spies and analysis team want me to tell you: 'There is an employee named Rick James in the CY_Labs database that does not actually exist. Find Rick’s date of birth and use it to locate and view a specific street in a city that is probably familiar to you. We believe that the legendary gif appears at that location during its street sweeping time.' Submit the street sweeping time as flag{<num>to<num><day>}. (ex: flag{6to7tuesday}) You can access the CY_Labs website [here](<link to CY_Labs site sql injection>)."""
tags = [ "sql" ]
files = []
flag = "flag{8to10monday}"
enabled = true