slug = "new-labs-1"
title = "New Labs 1"
author = "Ted"
value = 15
description = """We must again log into the admin account. CY_Labs is on lockdown so they have added some filtering to their login page. Our agents have discovered that they filtered the word “admin.” And yeah, we don’t even know how they log in as admin since they filter it. However, we believe in you. Good luck and report back once you’ve gained access."""
tags = [ "sql" ]
files = []
flag = "flag{top_secret}"
enabled = true