slug = "jibberish"
title = "J!bB3r!$H"
author = "Josh"
value = 10
description = """?! !@$%^%$!!!!@#@!! [!!!](http://attention-check.acmcyber.com:10000/jibberish)."""
tags = ["intro"]
files = []
flag = "flag{wardell_stephen_curry}"
enabled = true
